---
name: Cheng-Jung Hsieh
template: Neat Starter
author: Surjith S M
title: Software Engineer & Cybersecurity Specialist
email: cjhsieh1105@gmail.com
github: chengjunghsieh
linkedin: chengjunghsieh
description: MS Cybersecurity student at Georgia Tech with experience in software engineering and distributed systems
